apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-deployment
  name: my-deploylb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8501
  selector:
    app: my-deployment
  type: LoadBalancer
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - image: vijaynaik360/devops-fullcoarse:5789411ac9f463176e8808d660454b534f917e4c
        name: custom-image
        ports:
          - containerPort: 8501