pipeline{
    agent any
    environment{
        IMAGE_NAME = "vijaynaik360/devops-fullcoarse:${GIT_COMMIT}"
    }
    stages{
        stage("Git-Checkout"){
            steps{
                git url:"https://github.com/vijaynaik360/Devops-Fullcoarse.git",branch: 'main'
                }
            
            }
        stage("Build"){
            steps{
                sh '''
                        printenv 
                        pwd
                        cd code/
                        docker build -t ${IMAGE_NAME} .
                    '''
                }
            
            }
        // stage("Testing the iamge"){
        //     steps{
        //         sh '''
        //             docker kill c1 || true
        //             docker rm c1 || true
        //             docker run -d --name c1 -p 9001:8501 ${IMAGE_NAME}
        //             '''
        //         }
// }

        stage("Docker_hub Login"){
            steps{
               withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
    sh '''
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    '''
}
         }
            }

        stage("Push to Dockerhub"){
            steps{
                    sh '''
                        docker push ${IMAGE_NAME}
                    '''
                }

}
}
}