pipeline{
    agent any
    environment{
        IMAGE_NAME = "vijaynaik360/devops-fullcoarse:${GIT_COMMIT}"
        AWS_REGION = "us-east-1"
        CLUSTER_NAME = "microdegree-cluster"
        NAMESPACE = "microdegree"
    }
    stages{
        stage("Git-Checkout"){
            steps{
                git url:"https://github.com/vijaynaik360/Devops-Fullcoarse.git",branch: 'main'
                }
            
            }
        stage("Build"){
            steps{
                sh '''
                        printenv 
                        pwd
                        cd code/
                        docker build -t ${IMAGE_NAME} .
                    '''
                }
            
            }
        // stage("Testing the iamge"){
        //     steps{
        //         sh '''
        //             docker kill c1 || true
        //             docker rm c1 || true
        //             docker run -d --name c1 -p 9001:8501 ${IMAGE_NAME}
        //             '''
        //         }
// }

        stage("Docker_hub Login"){
            steps{
               withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
    sh '''
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    '''
}
         }
            }

        stage("Push to Dockerhub"){
            steps{
                    sh '''
                        docker push ${IMAGE_NAME}
                    '''
                }

}
        stage('Cluster-Update') {
                steps {
                    sh '''
                        aws eks update-kubeconfig \
                        --region ${AWS_REGION} \
                        --name ${CLUSTER_NAME}
                    '''
                }
            }

        stage('Deploying to EKS clsuter') {
                steps {
                    withKubeConfig(
                        caCertificate: '',
                        clusterName: 'microdegree',
                        contextName: '',
                        credentialsId: 'kube',
                        namespace: 'microdegree',
                        restrictKubeConfigAccess: false,
                        serverUrl: 'https://C15C267E4D23793587108D7BD4C327D3.gr7.us-east-1.eks.amazonaws.com'
                    ) {
                        sh '''
                          pwd
                          cd code
                          pwd
                          sed -i "s|replace|${IMAGE_NAME}|g" deployment.yaml 
                          kubectl apply -f deployment.yaml -n ${NAMESPACE}
                        '''
                    }
                }
            }

            stage('Verify the deployment') {
                steps {
                    withKubeConfig(
                        caCertificate: '',
                        clusterName: 'microdegree',
                        contextName: '',
                        credentialsId: 'kube',
                        namespace: 'microdegree',
                        restrictKubeConfigAccess: false,
                        serverUrl: 'https://C15C267E4D23793587108D7BD4C327D3.gr7.us-east-1.eks.amazonaws.com'
                    ) {
                        sh "kubectl get pods -n ${NAMESPACE}"
                        sh "kubectl get svc -n ${NAMESPACE}"
                    }
                }
            }        
}
}