pipeline{
    agent any
    environment{
        IMAGE_NAME = "vijaynaik360/devops-fullcoarse:${GIT_COMMIT}"
    }
    stages{
        stage("Git-Checkout"){
            steps{
                git url:"https://github.com/vijaynaik360/Devops-Fullcoarse.git",branch: 'main'
                }
            
            }
        stage("Build"){
            steps{
                sh '''
                        printenv 
                        pwd
                        cd code/
                        docker build -t ${IMAGE_NAME} .
                    '''
                }
            
            }
        stage("Testing the iamge"){
            steps{
                sh '''
                    doocker kill c1
                    docker rm c1
                    docker run -d --name c1 -p 9001:8501 ${IMAGE_NAME}
                    '''
                }
            
            }

}
}